apiVersion : apps/v1
kind: Deployment
metadata:
  name: todoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: k8sexamplesacr.azurecr.io/sampleapp
          securityContext:
          runAsUser: 0
          ports:
          - containerPort: 80